
import snakebids
from snakebids import bids


configfile: 'config/snakebids.yml'

#writes inputs_config.yml and updates config dict
config.update(snakebids.generate_inputs(bids_dir=config['bids_dir'],
                            pybids_inputs=config['pybids_inputs'],
                            derivatives=config['derivatives'],
                            participant_label=config['participant_label'],
                            exclude_participant_label=config['exclude_participant_label']))


#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(config['pybids_inputs'])



def get_all_input():
    if config["push_to_orthanc"]:
        return {
            "t1": expand(
                bids(
                    root="orthanc_push",
                    desc="done",
                    **config["input_wildcards"]["scan"],
                ),
                zip,
                **config["input_zip_lists"]["scan"]
            ),
          }
    else:
        return {
            "t1": expand(
                bids(
                    root="dicom",
                    **config["input_wildcards"]["scan"],
                ),
                zip,
                **config["input_zip_lists"]["scan"],
            ),
       }


rule all:
    input:
        **get_all_input()

rule nifti2dicom:
    input:
        config["input_path"]["scan"]
    output:
        directory(
            bids(
                root="dicom",
                **config["input_wildcards"]["scan"],
            )
        )
    container:
        "docker://tristankk/nifti2dicom:0.4.11"
    shell:
        "nifti2dicom -i {input} -o {output} -y --studyinstanceuid {config[studyinstanceuid]} --patientname {wildcards.subject}"

rule push_to_orthanc:
    input:
        bids(
            root="dicom",
            **config["input_wildcards"]["scan"],
        )
    output:
        touch(
            bids(
                root="orthanc_push",
                desc="done",
                **config["input_wildcards"]["scan"],
            )
        )
    script:
        "scripts/push_dicoms_to_orthanc.py"


